# Arquivo de configuracao padrao do webserv
server {
    listen              8080;
    server_name         localhost;

    error_page          404 /404.html;
    client_max_body_size 1M;

    location / {
        root            html;
        index           index.html;
        methods         GET;
        autoindex       on;
    }

    location /upload {
        root            html;
        methods         DELETE;
        upload_store    tmp/uploads;
    }

    location /cgi-bin {
        root            html;
        cgi             .py;
    }
}
